In [ ]:
8.	Reduce the data set in to 2 dimensional by using PCA. get top 2 principal components.
(Don't use the label column for this purpose). 
 State all principal components you got and how you chose top 2. 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing our cancer dataset
dataset = pd.read_csv('breast-cancer.csv')

In [3]:
dataset.head()

1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [4]:
X = dataset[dataset.columns[1:10]] 

In [5]:
X.head()

5   1  1.1  1.2  2 1.3  3  1.4  1.5
0  5   4    4    5  7  10  3    2    1
1  3   1    1    1  2   2  3    1    1
2  6   8    8    1  3   4  3    7    1
3  4   1    1    3  2   1  3    1    1
4  8  10   10    8  7  10  9    7    1

In [13]:
X.shape

(698, 9)

In [6]:

X = X.replace(to_replace ="?", 
                 value = 0) 
X.head()

5   1  1.1  1.2  2 1.3  3  1.4  1.5
0  5   4    4    5  7  10  3    2    1
1  3   1    1    1  2   2  3    1    1
2  6   8    8    1  3   4  3    7    1
3  4   1    1    3  2   1  3    1    1
4  8  10   10    8  7  10  9    7    1

In [7]:
Y = dataset[dataset.columns[10]]
Y = Y.replace(to_replace = "?", 
                 value = 0) 
Y.head()

0    2
1    2
2    2
3    2
4    4
Name: 2.1, dtype: int64

In [8]:
Y.shape

(698,)

In [9]:
from sklearn.preprocessing import StandardScaler as ss

In [10]:
from sklearn.decomposition import PCA

In [11]:
scale = ss()
X = scale.fit_transform(X)

In [12]:
pca = PCA()
out = pca.fit_transform(X)
out.shape 

(698, 9)

In [14]:
pca.explained_variance_ratio_

array([0.65409807, 0.08603047, 0.05982883, 0.05201108, 0.04232736,
       0.03381258, 0.03292862, 0.02907662, 0.00988636])

In [15]:
pca.explained_variance_ratio_.cumsum()


array([0.65409807, 0.74012854, 0.79995737, 0.85196845, 0.89429581,
       0.92810839, 0.96103701, 0.99011364, 1.        ])

In [20]:
data = out[:, :]
data

array([[ 1.46163639, -0.54386462,  0.27287155, ..., -0.993428  ,
         0.34625661,  0.01515543],
       [-1.57796215, -0.07635029,  0.03572397, ...,  0.23370576,
         0.23294266,  0.01753759],
       [ 1.504572  , -0.56062799, -0.60684514, ..., -0.24771476,
        -1.5963163 ,  0.18787681],
       ...,
       [ 3.8245378 , -0.18392167,  0.67317465, ...,  0.66304474,
        -0.53646157, -0.05754536],
       [ 2.26826043, -1.11441819,  0.99863985, ...,  1.67383465,
        -0.08362576,  0.41266165],
       [ 2.66251657, -1.19819703,  1.08273575, ...,  1.87187606,
        -0.31274806, -0.07490033]])

In [16]:
final_data = out[:, :2]


In [17]:
final_data.shape


(698, 2)

In [18]:
final_data

array([[ 1.46163639, -0.54386462],
       [-1.57796215, -0.07635029],
       [ 1.504572  , -0.56062799],
       ...,
       [ 3.8245378 , -0.18392167],
       [ 2.26826043, -1.11441819],
       [ 2.66251657, -1.19819703]])

In [ ]:
The dimensionality of the data has been reduced from 9 to 2.
The final_data has reduced dimensionality.