In [ ]:
Using SVM, build a tumor classifier. Use two different kernels and compare results. Upload your code along with a document of results. 
State the kernels you chose and the corresponding error rates

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing our cancer dataset
dataset = pd.read_csv('breast-cancer.csv')

In [2]:
dataset.head()

1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [3]:
X = dataset[dataset.columns[1:10]] 

In [4]:
X.head()

5   1  1.1  1.2  2 1.3  3  1.4  1.5
0  5   4    4    5  7  10  3    2    1
1  3   1    1    1  2   2  3    1    1
2  6   8    8    1  3   4  3    7    1
3  4   1    1    3  2   1  3    1    1
4  8  10   10    8  7  10  9    7    1

In [5]:
X.shape
X = X.replace(to_replace ="?", 
                 value = 0) 
X.head()

5   1  1.1  1.2  2 1.3  3  1.4  1.5
0  5   4    4    5  7  10  3    2    1
1  3   1    1    1  2   2  3    1    1
2  6   8    8    1  3   4  3    7    1
3  4   1    1    3  2   1  3    1    1
4  8  10   10    8  7  10  9    7    1

In [6]:
Y = dataset[dataset.columns[10]]
Y = Y.replace(to_replace = "?", 
                 value = 0) 
Y.head()

0    2
1    2
2    2
3    2
4    4
Name: 2.1, dtype: int64

In [7]:
Y.shape

(698,)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)

# Linear SVM

In [48]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
model = svclassifier.fit(X_train, y_train)
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [49]:
y_pred = svclassifier.predict(X_test)


In [50]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[79  1]
 [ 2 58]]
              precision    recall  f1-score   support

           2       0.98      0.99      0.98        80
           4       0.98      0.97      0.97        60

    accuracy                           0.98       140
   macro avg       0.98      0.98      0.98       140
weighted avg       0.98      0.98      0.98       140



In [51]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[79,  1],
       [ 2, 58]], dtype=int64)

In [52]:
from sklearn import metrics
a = metrics.accuracy_score(y_test, y_pred)
a

0.9785714285714285

In [53]:
error_rate = 1 - a
error_rate

0.021428571428571463

# Guaussian Kernal SVM

In [54]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

c:\users\sravya bhaskara\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [55]:
y_pred = svclassifier.predict(X_test)


In [56]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[74  6]
 [ 0 60]]
              precision    recall  f1-score   support

           2       1.00      0.93      0.96        80
           4       0.91      1.00      0.95        60

    accuracy                           0.96       140
   macro avg       0.95      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140



In [57]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[74,  6],
       [ 0, 60]], dtype=int64)

In [58]:
a = metrics.accuracy_score(y_test, y_pred)
a

0.9571428571428572

In [59]:
error_rate = 1 - a
error_rate

0.042857142857142816

The two different SVM classifiers are used
1. Linear SVM
2. Kernal SVM - Guassian Kernal

Linear SVM:
Linear SVMs can only classify linearly separable data
The accuracy of the model built using linear kernal is 97.85%
The error rate is 0.0214. That is, only 2 % of test data was misclassified.

Guassian Kernal
If the data isnt linearly separable, guassian kernals are used.
The accuracy of the model is 95.14%
The error rate is 0.042. Guassian kernal misclassifies 4 % of test data.
